# Licensed under the Apache License, Version 2.0.

[workspace]

members = [
    "rust/interop",
    "rust/base",
    "rust/transport",
    "rust/ipc",
    "rust/tesseract",
    "examples/rust/app_native",
    "examples/rust/wallet_native",
]

resolver = "1"
