# Licensed under the Apache License, Version 2.0.

[package]
name = "tesseract-android-base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
client = ["tesseract/client", "dep:async-trait"]
service = ["tesseract/service", "dep:async-trait"]

[dependencies]
thiserror = "1.0.31"
jni = "0.20.0"
jni_fn = "0.1.0"
log = "0.3.9"
android_log = "0.1.3"
futures = "0.3.21"

async-trait = {version="0.1", optional=true}
interop_android = { path = "../interop" }
tesseract = { path = "/Users/daniel/repo/Tesseract.rs/tesseract"}
#tesseract = {git = "https://github.com/tesseract-one/Tesseract.rs", branch="master"}
