# Licensed under the Apache License, Version 2.0.

[package]
name = "tesseract-android-library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["client", "service", "protocol-all"]

client = ["tesseract/client", "tesseract-android-base/client", "tesseract-android-transport/client", "dep:async-trait"]
service = ["tesseract/service", "tesseract-android-base/service", "tesseract-android-transport/service", "dep:async-trait"]

protocol-test = ["dep:tesseract-protocol-test"]
protocol-substrate = ["dep:tesseract-protocol-substrate"]
protocol-all = ["protocol-test", "protocol-substrate"]

[dependencies]
async-trait = { version="0.1", optional = true }

errorcon = "0.1"

#logger
log = "0.4"
log-panics = { version = "2", features = ["with-backtrace"] }
android_logger = "0.13"

#android interop
jni = "0.20"
jni_fn = "0.1"
crabdroid = { path = "../crabdroid" }

#tesseract
#tesseract = { path = "../../../Tesseract.rs/tesseract", features=["client", "service"]} 
tesseract = {git = "https://github.com/tesseract-one/Tesseract.rs", branch="master", features=["client", "service"]}
tesseract-android-base = { path = "../base" }
tesseract-android-transport = { path = "../transport" }

#protocols
#tesseract-protocol-test = { path = "../../../Tesseract.rs/protocols/test", optional=true, features=["client", "service"]}
#tesseract-protocol-substrate = { path = "../../../Tesseract.rs/protocols/substrate", optional=true, features=["client", "service"]}
tesseract-protocol-test = {git = "https://github.com/tesseract-one/Tesseract.rs", optional=true, branch="master", features=["client", "service"]}
tesseract-protocol-substrate = {git = "https://github.com/tesseract-one/Tesseract.rs", optional=true, branch="master", features=["client", "service"]}

[lib]
name = "tesseract"
crate-type = ["cdylib"]
