# Licensed under the Apache License, Version 2.0.

[package]
name = "tesseract-android-library"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["client", "service", "protocol-all"]

client = ["tesseract/client", "tesseract-android-base/client", "tesseract-android-transport/client", "dep:async-trait", "tesseract-android-ipc/client"]
service = ["tesseract/service", "tesseract-android-base/service", "tesseract-android-transport/service", "dep:async-trait"]

protocol-test = ["dep:tesseract-protocol-test"]
protocol-substrate = ["dep:tesseract-protocol-substrate"]
protocol-all = ["protocol-test", "protocol-substrate"]

[dependencies]
async-trait = { workspace = true, optional = true }

errorcon = { workspace = true }

#logger
log = { workspace = true }
log-panics = { workspace = true, features = ["with-backtrace"] }
android_logger = { workspace = true }

#android interop
jni = { workspace = true }
jni_fn = { workspace = true }
crabdroid = { path = "../crabdroid" }

#tesseract
tesseract = { workspace = true, features = ["client", "service"] } 

#tesseract.android
tesseract-android-base = { path = "../base" }
tesseract-android-transport = { path = "../transport" }
tesseract-android-ipc = { path = "../ipc" }

#protocols
tesseract-protocol-test = { workspace = true, optional = true, features = ["client", "service"]}
tesseract-protocol-substrate = { workspace = true, optional = true, features = ["client", "service"]}

[lib]
name = "tesseract"
crate-type = ["cdylib"]
