# Licensed under the Apache License, Version 2.0.

[package]
name = "wallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
thiserror = "1.0"
errorcon = "0.1"

#logger
log = "0.4"
log-panics = { version = "2", features = ["with-backtrace"] }
android_logger = "0.13"

#android interop
jni = "0.20"
jni_fn = "0.1"
crabdroid = { path = "../../../rust/crabdroid", features = ["thread-pool"]}

#tesseract
#tesseract = { path = "../../../../Tesseract.rs/tesseract", features=["service"]} 
#tesseract-protocol-test = { path = "../../../../Tesseract.rs/protocols/test", features=["service"]}
tesseract = {git = "https://github.com/tesseract-one/Tesseract.rs", branch="master", features=["service"]}
tesseract-protocol-test = {git = "https://github.com/tesseract-one/Tesseract.rs", branch="master", features=["service"]}

tesseract-android = { path = "../../../rust/sdk", features=["service"]}

[lib]
crate_type = ["cdylib"]
