# Licensed under the Apache License, Version 2.0.

[package]
name = "tesseract-android-ipc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["service"]
client = ["tesseract/client", "tesseract-android-transport/client", "dep:async-trait"]
service = ["tesseract/service", "tesseract-android-transport/service", "dep:async-trait"]

[dependencies]
async-trait = {version="0.1", optional=true}

thiserror = "1.0.31"
log = "0.3.9"
futures = "0.3.21"

jni = "0.20.0"
jni_fn = "0.1.0"
android_log = "0.1.3"
crabdroid = { path = "../crabdroid" }

tesseract = { path = "/Users/daniel/repo/Tesseract.rs/tesseract"}
tesseract-android-transport = { path = "../transport" }
#tesseract = {git = "https://github.com/tesseract-one/Tesseract.rs", branch="master"}
