# Licensed under the Apache License, Version 2.0.

[package]
name = "tesseract-android-transport"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
client = ["tesseract/client", "tesseract-android-base/client"]
service = ["tesseract/service", "tesseract-android-base/service"]

[dependencies]
log = "0.3.9"

jni = "0.20.0"
jni_fn = "0.1.0"
crabdroid = { path = "../crabdroid" }

tesseract = { path = "/Users/daniel/repo/Tesseract.rs/tesseract"} #tesseract = {git = "https://github.com/tesseract-one/Tesseract.rs", branch="master"}
tesseract-android-base = { path = "../base" }
